### PR TITLE
Updating Oswald math symbols

### LINKED ISSUE #18: Mathematical signs are misaligned
The horizontal bar of + − ÷ should be the same, and aligned vertically (in the middle) with × =.
Oswald

### PR DESCRIPTION
**Pull request by aaronbell**
Improving alignment of math symbols for better rendering. Closes #18.
Screen Shot 2021-09-13 at 3 07 17 PM

Bump version string to 4.103.

### CODE REVIEW

**Comment by aaronbell** [comment]
I'm not sure if an email got sent out for this while I was `spammy`, so wanted to follow up on it.

**Comment by aaronbell** [comment]
Following up :)

**Comment by aaronbell** [comment]
@RosaWagner Ping :)

**Comment by RosaWagner** [comment]
Yeah I don't know what to do cause previous PR form Marc is still pending and this one come in conflict with it. 
cc @m4rc1e

**Comment by aaronbell** [comment]
I fixed the same kern issue that Marc pointed out in his version and, as these fonts are now being run through UFR, the gftools “fix-hinting “ fix should be being applied automatically, though that is only really applicable for the static instances.

All in all I think we can close his PR.

**Comment by dom1n1k** [comment]
Actually is still the old version on Google Fonts.
I checked on the site and in Figma.

Screenshot

**Pull request merged**
