### PR TITLE
Fix dead link

### PR DESCRIPTION
**Pull request by MrBrain295**

### CODE REVIEW

**Comment by fitojb** [comment]
It’s more helpful to find the new location of a pointed resource instead of just removing the broken link.

**Comment by MrBrain295** [comment]
I couldn’t find a new link.

**Comment by MrBrain295** [comment]
I replaced the link.

**Comment by MrBrain295** [comment]
Is this mergeable?

**Comment by MrBrain295** [comment]
@emmamarichal can you merge this?

**Pull request merged**
