### PR TITLE
Added Cyrillic Glyphs

### PR DESCRIPTION
**Pull request by NDISCOVER**
Added Cyrillic Glyphs + Started Kerning Revision

### CODE REVIEW

**Comment by NDISCOVER** [comment]
@davelab6 here is the pull request :)

**Comment by davelab6** [comment]
The red ones will be added in the next few weeks

**Comment by m4rc1e** [comment]
@davelab6 If we need this for next week. shall I remove the red glyphs and send a pr to google/fonts?

If so, please merge this pr (I'm happy with it) and I will polish it.

**Comment by davelab6** [comment]
You can just mark the red glyphs as not for export

**Comment by davelab6** [comment]
And yes this is needed asap

**Comment by alexeiva** [comment]
The Cyrillic looks good enough for a quick first release as is.
I will prepare a specific fine-tuning review that you can implement in the next update.

**Pull request merged**
