### PR TITLE
Oswald Cyrillic Pro Support

### PR DESCRIPTION
**Pull request by NDISCOVER**
• Complete Cyrillic Pro Support.
Design + Kerning
(Didn't change the original basic Cyrillic design, but needs some improvement in future)

• Latin Improvement
Minimal Design Adjustments on Latin
Kerning Re-done (created new classes and new kerning values altogether)

### CODE REVIEW

**Comment by NDISCOVER** [comment]
@davelab6 Hey Dave, here is the pull request! :)

**Comment by davelab6** [comment]
Please sign the cla with the email your git is configured with

**Comment by NDISCOVER** [comment]
Do I need to create a Google group? I am stuck at that step of the signing process.

NDISCOVER
Digital Typography

**Comment by davelab6** [comment]
No, definitely not :)

**Comment by NDISCOVER** [comment]
Is it done already? 
Omg I am so not tech savvy xD

**Comment by m4rc1e** [comment]
This pr introduces some regressions

screen shot 2018-06-19 at 16 03 15.

Love the effort though.

**Comment by NDISCOVER** [comment]
I fixed the source file, ttfs and otfs, but I can't remember how to do the pull request.
It is updated in my repo.

**Comment by davelab6** [comment]
Closing as done in #11

**Pull request closed without merging**
